// modules/wyrt_admin/www/components/ServerStatus.tsx
'use client';

interface ServerStatusProps {
  status: boolean;
}

export default function ServerStatus({ status }: ServerStatusProps) {
  return (
    <div className="flex items-center space-x-2">
      <div className={`w-3 h-3 rounded-full ${status ? 'bg-green-500' : 'bg-red-500'} animate-pulse`}></div>
      <span className="text-sm font-medium text-gray-700">
        {status ? 'Connected' : 'Disconnected'}
      </span>
    </div>
  );
}

// www/src/components/ServerStatus.vue
<template>
    <a href="#" class="flex items-center px-4 py-2 text-gray-100 hover:bg-gray-700 group">
        <span class="h-6 w-6 rounded-full inline-block mr-2" :class="props.status ? 'bg-green-700' : 'bg-red-700'"></span>
        {{ props.status ? 'Connected' : 'Disconnected' }}
    </a>
</template>
<script setup lang="ts">
const props = defineProps({
    status: { type: Boolean, required: true },
})
</script>
